#!/usr/bin/env bash
#installs nginx, listens on port 80, and returns a page with a string

apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
