#!/usr/bin/env bash
# a bash script that configures a new ubuntu machine:

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /usr/share/nginx/html/index.html
sudo service nginx restart
