#!/usr/bin/env bash
# This script is displaying the content of the file /etc/passwd
# shellcheck disable=SC2162
# shellcheck disable=SC2086
while read line; do
    echo $line $1 $3 $6
done </etc/passwd
