#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes
hour=0
while (("$hour" < 13)); do
    minutes=1
    echo "Hour:" $hour
    while (("minutes" < 60)); do
        echo $minutes
        ((minutes++))
    done
    ((hour++))
done
