#!/usr/bin/env bash
# Let’s install the ufw firewall and setup a few rules on web-01.
sudo ufw --force reset
sudo apt -y update
sudo apt -y install ufw
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw --force enable
